### ISSUE TITLE
User Stories Complete

### ISSUE THREAD

**Issue by nt92** [Vente-Bringing-Humanity-Together/Vente#1]
/cc @codepathreview @codepath

Got our required and 5 levels of optionals.

**Comment by minhkhang1795** [comment]
:+1: Great to see your GitHub repository setup and user stories defined! The user stories are a key piece of the group project. They help you prioritize the most important parts of the app to build. It's particularly important that you've split the user stories into "Required" and "Optional" stories so your team can focus on the most important aspects of the app first and then add in the optionals as time permits toward the end of the project.

Next week we'll move on to the next step of the group project by doing something called wireframing, which is creating a blueprint for the app.
